services:
  database:
    image: mariadb:10
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${MYSQL_DB_NAME}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'dbdata:/var/lib/mysql'
  database_testing:
    image: mariadb:10
    ports:
      - '${MYSQL_PORT_TESTING}:3306'
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${MYSQL_DB_NAME}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'dbdatatesting:/var/lib/mysql'
volumes:
  dbdata:
    driver: local
  dbdatatesting:
    driver: local

