name: Run tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install the dependancies
        run: npm ci
      - name: End message
        run: echo 'All done!'